@startuml 電気長切断Usecase
left to right direction
rectangle PC {
    (作業者メンテ)
    (製番メンテ)
    (品番メンテ)
    (ケーブル切断)
    (記録) .> (記録印刷)
}
(ネットワークアナライザ)

:作業者: --> (ケーブル切断)
:作業者: --> (記録)
:作業者: --> (記録印刷)
:管理者: --> (作業者メンテ)
:管理者: --> (製番メンテ)
:管理者: --> (品番メンテ)
(ネットワークアナライザ) .> (ケーブル切断)
@enduml