@startuml PASTrans Sequence
!theme spacelab
PAS -> ImgTrans  : $success("起動、情報を渡す")
ImgTrans -> Camera  : $success("撮影要求")
Camera -> ImgTrans  : $success("画像")
ImgTrans -> Server : $success("画像データhttp送信")
Server -> ImgTrans : $success("インデックス等受信")
ImgTrans -> CSVファイル : $success("シリアル、インデックスを保存")
CSVファイル -> ImgTrans
ImgTrans -> PAS : $success("終了。制御を戻す")

@enduml