@startuml アプリケーションエラー発生シーケンス
k670_MSE762 -> GetProfileChar : '--------------送信Log---------------------------' 文字列読み込み要求
k670_MSE762 <- GetProfileChar : 読み込み終了
k670_MSE762 -> GetProfileChar : "動作" 文字列読み込み要求
note right : 読み込みに失敗すると、\n読み出しバッファは\n"--------------送信Log---------------------------"のまま
k670_MSE762 <- GetProfileChar : 読み込み終了
note left : 読み出しバッファの内容(48Byte)を\n10バイトのログ出力準備バッファに\nコピーしようとしてアプリケーションエラー\n発生
@enduml
