@startuml PASImageTransferクラス図
!theme spacelab
class CPASImageTransferApp
{
    #各クラスインスタンスのポインタ
    #InitInstance()
}
note right of CPASImageTransferApp
アプリケーションクラス
end note

class CAboutDlg
{
    +DoModal()
}
note bottom of CAboutDlg
バージョン情報の表示機能
end note

class CErrorLog
{
    +AddErrot()
}
note bottom of CErrorLog
エラーログ書き出し機能
end note

class CWebcam
{
    +SaveImage()
    +ShowMovie()
}
note bottom of CWebcam
カメラから画像取得機能
end note

class CSettingFile
{
    +各パラメータの取得関数
    +各パラメータの設定関数
}
note bottom of CSettingFile
設定ファイル読み込み機能
end note

class CSrvCom
{
    +SendData()
}
note bottom of CSrvCom
サーバーとの通信機能
end note

class GrobalFunction
{
    +GetSerialFileName()
    +GetExecFolder()
    +AddYen()
    +base64_encode()
    +AddLine()
}
note bottom of GrobalFunction
共通関数
end note

CPASImageTransferApp --* CWebcam
CPASImageTransferApp --* CSettingFile
CPASImageTransferApp --* CErrorLog
CPASImageTransferApp --* CAboutDlg
CPASImageTransferApp --* CSrvCom
CPASImageTransferApp --* GrobalFunction

@enduml